### ISSUE TITLE
Meteor Example fill pdf template with data from a Collection

### ISSUE THREAD

**Issue by dfuchs2512** [aadamsx/meteor-pdftk#5]
Hello, 

I was searching arround but could not find a good example to use Meteor-pdftk with a given pdf template and generate a pdf with data from a collection. My task I would like to accomplish is the following.

I have a given pdf template (like a certificate which contains images and empty fields. The empty fields should be filled with data from a collection and the pdf should be shown on the client side. Each time when I proceed a query on the collection it will return me the fields that I want to fill in this pdf template.

Can you provide a simple example to make this task happen.

Regards,

Daniel alias dfuchs2512

**Comment by aadamsx** [comment]
"I was searching around but could not find a good example to use Meteor-pdftk with a given pdf template and generate a pdf with data from a collection." That's probably because not a lot of Meteor devs have done this, and the ones that have probably have not posted on how they did it (yet).

I couldn't find a way to do it when I started, and had to come up with a solution myself.  That's one of the reasons I built and published this package.

The examples in the readme should get you started.  Do you have a specific question?  Sounds like you don't know where to start and your asking for instructions on how to do this from the point where you have data in your collection -- am I right?

**Comment by dfuchs2512** [comment]
Yes thats right. I dont really know where to start. Maybe you have some working example which I can use. My starting point is I just have a pdf template. And my app is generating a list with people out of a collection. When I select one of the people in the list I get detailed information from a other collection, which can containe different numer of documents. I take informations from this documents and want to generate a pdf file with this data, which I can show in a special meteor-template. Like a smal preview of the generated pdf.

Hope you can get me a little startup help.

Thanks.

Daniel

**Comment by aadamsx** [comment]
There's much more to it than having data in a collection of course -- this is the easy part.  Getting the data into the Form is more work.  I don't have a working example for you to follow right now, and there are a lot of small steps and thinks to know/understand about the PDF condition/format -- and frankly it can get a little complex with all the moving parts, where this package is just one component.  

Unfortunately, I'm building a software business right now, and besides it will take a fully working small but complex application to show you how all the moving parts work and function.  

But right now, coincidentally, I am doing this exact same thing for a new portion/slice of my software from start to finish, so I'm open to talk.

**Comment by dfuchs2512** [comment]
Ok, I saw from the readme the command fillform(pdf, xfdf, output). I guess the pdf is my Template pdf? and the xfdf file is the Data File for the pdf. And the Output is the pdf with the filled in data?

- How I call this command from my Meteor Client (maybe as a Method???) 
- How the syntax looks like? 
- And how I get my data from the collection in to this xfdf file?

**Comment by aadamsx** [comment]
Again, sorry friend, I'm building a software business right now and unfortunately don't have the cycles to do this for you.  I could help you, but I'm not consulting for free right now, as it would take away from my project.

It took me a little while go get through it all with all the moving parts, and I didn't have this package as a stepping stone -- so you should have a easier time of it.

Best of luck.

**Comment by dfuchs2512** [comment]
I understand. Thank you so far.
